# Generated by Django 4.2 on 2023-04-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imgage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
