# Generated by Django 4.2 on 2023-04-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_imgage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='imgage',
            new_name='image',
        ),
    ]
